version: '3.8'
services:
  talmoapi:
    build: .
    container_name: talmoapi
    ports:
      - "1542:1542"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs